//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduling.Business.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ppmoney.com/", ConfigurationName="TestService.userService")]
    public interface userService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JobScheduling.Business.TestService.getUserResponse getUser(JobScheduling.Business.TestService.getUser request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JobScheduling.Business.TestService.getInfoResponse getInfo(JobScheduling.Business.TestService.getInfo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ppmoney.com/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string infoField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://service.ppmoney.com/", IsWrapped=true)]
    public partial class getUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ppmoney.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public getUser() {
        }
        
        public getUser(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://service.ppmoney.com/", IsWrapped=true)]
    public partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ppmoney.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JobScheduling.Business.TestService.user @return;
        
        public getUserResponse() {
        }
        
        public getUserResponse(JobScheduling.Business.TestService.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfo", WrapperNamespace="http://service.ppmoney.com/", IsWrapped=true)]
    public partial class getInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ppmoney.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public getInfo() {
        }
        
        public getInfo(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoResponse", WrapperNamespace="http://service.ppmoney.com/", IsWrapped=true)]
    public partial class getInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.ppmoney.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getInfoResponse() {
        }
        
        public getInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface userServiceChannel : JobScheduling.Business.TestService.userService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class userServiceClient : System.ServiceModel.ClientBase<JobScheduling.Business.TestService.userService>, JobScheduling.Business.TestService.userService {
        
        public userServiceClient() {
        }
        
        public userServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public userServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobScheduling.Business.TestService.getUserResponse JobScheduling.Business.TestService.userService.getUser(JobScheduling.Business.TestService.getUser request) {
            return base.Channel.getUser(request);
        }
        
        public JobScheduling.Business.TestService.user getUser(string name) {
            JobScheduling.Business.TestService.getUser inValue = new JobScheduling.Business.TestService.getUser();
            inValue.name = name;
            JobScheduling.Business.TestService.getUserResponse retVal = ((JobScheduling.Business.TestService.userService)(this)).getUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JobScheduling.Business.TestService.getInfoResponse JobScheduling.Business.TestService.userService.getInfo(JobScheduling.Business.TestService.getInfo request) {
            return base.Channel.getInfo(request);
        }
        
        public string getInfo(string name) {
            JobScheduling.Business.TestService.getInfo inValue = new JobScheduling.Business.TestService.getInfo();
            inValue.name = name;
            JobScheduling.Business.TestService.getInfoResponse retVal = ((JobScheduling.Business.TestService.userService)(this)).getInfo(inValue);
            return retVal.@return;
        }
    }
}
